
import { VoiceOption, ThemeOption, Language } from './types';

export const LANGUAGES = [
  { id: 'id', label: 'Indonesian (Indonesia)', icon: '🇮🇩' },
  { id: 'en', label: 'English (United States)', icon: '🇺🇸' },
  { id: 'ar', label: 'Arabic (العربية)', icon: '🇸🇦' },
  { id: 'jp', label: 'Japanese (日本語)', icon: '🇯🇵' },
  { id: 'es', label: 'Spanish (Español)', icon: '🇪🇸' },
  { id: 'fr', label: 'French (Français)', icon: '🇫🇷' },
  { id: 'de', label: 'German (Deutsch)', icon: '🇩🇪' },
  { id: 'zh', label: 'Chinese (中文)', icon: '🇨🇳' },
  { id: 'ko', label: 'Korean (한국어)', icon: '🇰🇷' },
  { id: 'hi', label: 'Hindi (हिन्दी)', icon: '🇮🇳' },
  { id: 'pt', label: 'Portuguese (Português)', icon: '🇵🇹' },
  { id: 'ru', label: 'Russian (Русский)', icon: '🇷🇺' },
  { id: 'it', label: 'Italian (Italiano)', icon: '🇮🇹' },
  { id: 'tr', label: 'Turkish (Türkçe)', icon: '🇹🇷' },
  { id: 'vi', label: 'Vietnamese (Tiếng Việt)', icon: '🇻🇳' },
  { id: 'th', label: 'Thai (ไทย)', icon: '🇹🇭' },
  { id: 'nl', label: 'Dutch (Nederlands)', icon: '🇳🇱' },
  { id: 'pl', label: 'Polish (Polski)', icon: '🇵🇱' },
];

const BASE_TRANSLATION = {
  appName: "CONTENT WAREHOUSE PRO",
  appSub: "All-In-One AI Creator Studio",
  sec1: "1. Script & Visuals",
  sec2: "2. Character & Style",
  placeholderTopic: "Main Topic Title...",
  placeholderScript: "Write or generate voice script here...",
  btnSuggest: "✨ Suggest",
  btnScript: "📝 Make Script",
  btnVisual: "🖼️ Make Visual",
  lblPara: "Narrative",
  lblVisual: "Visual Count",
  lblVoice: "Base Character",
  lblStyle: "Speech Style",
  lblEmotion: "Emotional Expression",
  lblGallery: "Visual Gallery",
  btnDeleteGallery: "🗑️ Clear Gallery",
  btnDownloadAll: "🚀 Download All",
  hookTitle: "🔥 YouTube Viral Hook",
  hookSub: "Automatic Clickbait trigger...",
  thumbTitle: "📸 Thumbnail Overlay",
  thumbSub: "Catchy 4-7 word phrase...",
  seoTitle: "🔍 SEO METADATA (DESC & TAGS)",
  seoSub: "Search Ranking Optimization",
  btnSeo: "🚀 Generate Full SEO",
  lblDesc: "YouTube Description",
  lblTags: "YouTube Tags (SEO)",
  btnStudio: "🎙️ Generate Full Studio",
  btnStop: "⏹️ Stop",
  btnPlay: "▶️ Play Now",
  btnSave: "💾 Save MP3",
  footer: "All-In-One AI Creator Studio",
  copy: "Copy",
  clear: "Clear",
  generateSeoLoading: "⏳ Brewing...",
  suggestLoading: "⏳...",
  titleLabel: "Title",
  descLabel: "Description",
  tagsLabel: "Tags",
  thumbTextLabel: "Thumbnail Text",
  langLabel: "Select Content Language",
  // Script Themes
  themeReligious: "Religious/Spiritual",
  themeHorror: "Mystery/Horror",
  themeStory: "Storytelling/Kids",
  themePoetry: "Poetry/Quotes",
  themeComedy: "Comedy/Sketches",
  themeReview: "Reviews/Anime",
  themeAds: "Advertisement",
  themeFinance: "Business/Finance",
  themeEdu: "Education",
  themeTech: "Tech/Gadgets",
  themeHistory: "History/Facts",
  themeCulinary: "Culinary",
  themeTravel: "Travel/Nature"
};

export const TRANSLATIONS: Record<string, any> = {
  id: {
    ...BASE_TRANSLATION,
    appName: "GUDANG KONTEN PRO",
    appSub: "Studio Kreator All-In-One AI",
    sec1: "1. Naskah & Visual",
    sec2: "2. Karakter & Gaya",
    placeholderTopic: "Judul Topik Utama...",
    placeholderScript: "Tulis atau hasilkan naskah suara di sini...",
    btnSuggest: "✨ Saran",
    btnScript: "📝 Buat Naskah",
    btnVisual: "🖼️ Buat Visual",
    lblPara: "Narasi",
    lblVisual: "Jumlah Visual",
    lblVoice: "Karakter Dasar",
    lblStyle: "Gaya Bicara",
    lblEmotion: "Ekspresi Emosi",
    lblGallery: "Visual Gallery",
    btnDeleteGallery: "🗑️ Hapus Galeri",
    btnDownloadAll: "🚀 Download Semua",
    hookTitle: "🔥 YouTube Viral Hook",
    hookSub: "Pemicu klik (Clickbait) otomatis...",
    thumbTitle: "📸 Thumbnail Overlay",
    thumbSub: "Kalimat pancingan 4-7 kata...",
    seoTitle: "🔍 SEO METADATA (DESKRIPSI & TAGS)",
    seoSub: "Optimasi Peringkat Pencarian Video",
    btnSeo: "🚀 Buat SEO Lengkap",
    lblDesc: "YouTube Description",
    lblTags: "YouTube Tags (SEO)",
    btnStudio: "🎙️ Hasilkan Studio Lengkap",
    btnStop: "⏹️ Berhenti",
    btnPlay: "▶️ Putar Sekarang",
    btnSave: "💾 Simpan MP3",
    footer: "Studio Kreator All-In-One AI",
    copy: "Salin",
    clear: "Bersihkan",
    generateSeoLoading: "⏳ Sedang Meracik...",
    suggestLoading: "⏳...",
    titleLabel: "Judul",
    descLabel: "Deskripsi",
    tagsLabel: "Tags",
    thumbTextLabel: "Teks Thumbnail",
    langLabel: "Pilih Bahasa Konten",
    themeReligious: "Dakwah/Religi",
    themeHorror: "Misteri/Horor",
    themeStory: "Dongeng/Anak",
    themePoetry: "Puisi/Quotes",
    themeComedy: "Komedi/Sketsa",
    themeReview: "Review/Anime",
    themeAds: "Iklan/Promosi",
    themeFinance: "Bisnis/Keuangan",
    themeEdu: "Edukasi/Tutorial",
    themeTech: "Teknologi/Gadget",
    themeHistory: "Sejarah/Fakta",
    themeCulinary: "Kuliner/Resep",
    themeTravel: "Travel/Alam"
  },
  en: BASE_TRANSLATION,
  ar: {
    ...BASE_TRANSLATION,
    appName: "مستودع المحتوى برو",
    appSub: "استوديو المبدعين المتكامل بالذكاء الاصطناعي",
    sec1: "1. النص والمرئيات",
    sec2: "2. الشخصية والأسلوب",
    placeholderTopic: "عنوان الموضوع الرئيسي...",
    placeholderScript: "اكتب أو أنشئ نصًا صوتيًا هنا...",
    btnSuggest: "✨ اقتراح",
    btnScript: "📝 إنشاء نص",
    btnVisual: "🖼️ إنشاء صور",
    lblPara: "السرد",
    lblVisual: "عدد الصور",
    lblVoice: "الشخصية الأساسية",
    lblStyle: "أسلوب الكلام",
    lblEmotion: "التعبير العاطفي",
    lblGallery: "معرض الصور",
    btnDeleteGallery: "🗑️ مسح المعرض",
    btnDownloadAll: "🚀 تحميل الكل",
    hookTitle: "🔥 عنوان يوتيوب الفيروسي",
    hookSub: "محفز كليك بيت تلقائي...",
    thumbTitle: "📸 نص الصورة المصغرة",
    thumbSub: "جملة جذابة من 4-7 كلمات...",
    seoTitle: "🔍 بيانات SEO (الوصف والتاجات)",
    seoSub: "تحسين ترتيب البحث للفيديو",
    btnSeo: "🚀 إنشاء SEO كامل",
    lblDesc: "وصف يوتيوب",
    lblTags: "كلمات يوتيوب (SEO)",
    btnStudio: "🎙️ إنتاج الاستوديو بالكامل",
    btnStop: "⏹️ إيقاف",
    btnPlay: "▶️ تشغيل الآن",
    btnSave: "💾 حفظ MP3",
    copy: "نسخ",
    clear: "مسح",
    langLabel: "اختر لغة المحتوى",
    themeReligious: "ديني/روحاني",
    themeHorror: "غموض/رعب",
    themeStory: "قصص/أطفال",
    themePoetry: "شعر/اقتباسات",
    themeComedy: "كوميديا",
    themeReview: "مراجعات",
    themeAds: "إعلانات",
    themeFinance: "أعمال/تمويل",
    themeEdu: "تعليم",
    themeTech: "تقنية",
    themeHistory: "تاريخ/حقائق",
    themeCulinary: "طبخ",
    themeTravel: "سفر"
  },
  jp: {
    ...BASE_TRANSLATION,
    appName: "コンテンツ倉庫 PRO",
    appSub: "オールインワンAIクリエイタースタジオ",
    sec1: "1. 台本とビジュアル",
    sec2: "2. キャラクターとスタイル",
    placeholderTopic: "メインタイトルのトピック...",
    placeholderScript: "ここにボイススクリプトを書くか生成してください...",
    btnSuggest: "✨ 提案",
    btnScript: "📝 台本作成",
    btnVisual: "🖼️ ビジュアル作成",
    lblPara: "ナレーション",
    lblVisual: "ビジュアル数",
    lblVoice: "基本キャラクター",
    lblStyle: "話し方",
    lblEmotion: "感情表現",
    lblGallery: "ビジュアルギャラリー",
    btnDeleteGallery: "🗑️ ギャラリーをクリア",
    btnDownloadAll: "🚀 すべてダウンロード",
    hookTitle: "🔥 YouTubeバズタイトル",
    hookSub: "自動クリックベイトトリガー...",
    thumbTitle: "📸 サムネイルテキスト",
    thumbSub: "キャッチーな4-7語のフレーズ...",
    seoTitle: "🔍 SEOメタデータ（説明とタグ）",
    seoSub: "ビデオ検索ランキングの最適化",
    btnSeo: "🚀 フルSEO生成",
    lblDesc: "YouTube説明文",
    lblTags: "YouTubeタグ (SEO)",
    btnStudio: "🎙️ フルスタジオ生成",
    btnStop: "停止",
    btnPlay: "再生",
    btnSave: "MP3保存",
    copy: "コピー",
    clear: "クリア",
    langLabel: "コンテンツ言語の選択",
    themeReligious: "宗教/スピリチュアル",
    themeHorror: "ミステリー/ホラー",
    themeStory: "ストーリー/子供",
    themePoetry: "詩/引用",
    themeComedy: "コメディ",
    themeReview: "レビュー",
    themeAds: "広告",
    themeFinance: "ビジネス/金融",
    themeEdu: "教育",
    themeTech: "テック",
    themeHistory: "歴史",
    themeCulinary: "料理",
    themeTravel: "旅行"
  },
  es: {
    ...BASE_TRANSLATION,
    appName: "ALMACÉN DE CONTENIDO PRO",
    appSub: "Estudio Creativo AI Todo en Uno",
    sec1: "1. Guión y Visuales",
    sec2: "2. Personaje y Estilo",
    placeholderTopic: "Título del tema principal...",
    placeholderScript: "Escriba o genere el guión de voz aquí...",
    btnSuggest: "✨ Sugerir",
    btnScript: "📝 Crear Guión",
    btnVisual: "🖼️ Crear Visual",
    lblPara: "Narrativa",
    lblVisual: "Cantidad de Visuales",
    lblVoice: "Personaje Base",
    lblStyle: "Estilo de Habla",
    lblEmotion: "Expresión Emocional",
    lblGallery: "Galería Visual",
    btnDeleteGallery: "🗑️ Limpiar Galería",
    btnDownloadAll: "🚀 Descargar Todo",
    hookTitle: "🔥 Gancho Viral de YouTube",
    hookSub: "Activador automático de Clickbait...",
    thumbTitle: "📸 Superposición de Miniatura",
    thumbSub: "Frase pegadiza de 4-7 palabras...",
    seoTitle: "🔍 METADATOS SEO (DESC y TAGS)",
    seoSub: "Optimización de Ranking de Búsqueda",
    btnSeo: "🚀 Generar SEO Completo",
    lblDesc: "Descripción de YouTube",
    lblTags: "Etiquetas de YouTube (SEO)",
    btnStudio: "🎙️ Generar Estudio Completo",
    btnStop: "⏹️ Detener",
    btnPlay: "▶️ Reproducir Ahora",
    btnSave: "💾 Guardar MP3",
    copy: "Copiar",
    clear: "Limpiar",
    langLabel: "Seleccionar Idioma del Contenido",
    themeReligious: "Religioso/Espiritual",
    themeHorror: "Misterio/Horror",
    themeStory: "Cuentos/Niños",
    themePoetry: "Poesía",
    themeComedy: "Comedia",
    themeReview: "Reseñas",
    themeAds: "Anuncio",
    themeFinance: "Negocios/Finanzas",
    themeEdu: "Educación",
    themeTech: "Tecnología",
    themeHistory: "Historia",
    themeCulinary: "Culinario",
    themeTravel: "Viajes"
  }
};

// Add fallbacks for other languages to English base
LANGUAGES.forEach(lang => {
  if (!TRANSLATIONS[lang.id]) {
    TRANSLATIONS[lang.id] = { ...BASE_TRANSLATION, langLabel: `Select Content Language (${lang.label})` };
  }
});

export const VOICES: VoiceOption[] = [
  { id: 'Kore', label: 'Kore - Professional', description: 'Authoritative voice.', gender: 'Female', previewText: 'Voice check.' },
  { id: 'Zephyr', label: 'Zephyr - Friendly', description: 'Warm and soothing.', gender: 'Female', previewText: 'Voice check.' },
  { id: 'Puck', label: 'Puck - Energetic', description: 'Youthful and high energy.', gender: 'Male', previewText: 'Voice check.' },
  { id: 'Charon', label: 'Charon - Documentary', description: 'Deep and stable.', gender: 'Male', previewText: 'Voice check.' },
  { id: 'Fenrir', label: 'Fenrir - Cinematic', description: 'Dark and heavy.', gender: 'Male', previewText: 'Voice check.' }
];

export const EMOTIONS = [
  { id: 'normally', label: 'Normal', icon: '😐' },
  { id: 'cheerfully', label: 'Cheerful', icon: '😊' },
  { id: 'excitedly', label: 'Excited', icon: '🤩' },
  { id: 'calmly', label: 'Calm', icon: '🧘' },
  { id: 'seriously', label: 'Serious', icon: '🧐' },
  { id: 'sadly', label: 'Sad', icon: '😢' },
  { id: 'boldly', label: 'Bold', icon: '🛡️' },
  { id: 'horrified', label: 'Horrifying', icon: '👻' },
  { id: 'mysterious', label: 'Mysterious', icon: '🕵️' },
  { id: 'angry', label: 'Angry', icon: '😡' },
  { id: 'funny', label: 'Funny', icon: '🤡' },
];

export const SPEECH_STYLES = [
  { id: 'default', label: 'Standard', icon: '🎙️' },
  { id: 'ustadz', label: 'Wise', icon: '🕌' },
  { id: 'news', label: 'News Anchor', icon: '📺' },
  { id: 'influencer', label: 'Vlogger', icon: '🤳' },
  { id: 'teacher', label: 'Teacher', icon: '👨‍🏫' },
  { id: 'sales', label: 'Sales/Ads', icon: '💰' },
  { id: 'robot', label: 'Robot', icon: '🤖' },
  { id: 'storyteller', label: 'Storyteller', icon: '📖' },
  { id: 'motivator', label: 'Motivator', icon: '🔥' },
];

export const SCRIPT_THEMES = [
  { id: 'islam_dakwah', labelKey: 'themeReligious' },
  { id: 'horror_mystery', labelKey: 'themeHorror' },
  { id: 'storytelling', labelKey: 'themeStory' },
  { id: 'poetry', labelKey: 'themePoetry' },
  { id: 'comedy', labelKey: 'themeComedy' },
  { id: 'movie_review', labelKey: 'themeReview' },
  { id: 'ads_hard', labelKey: 'themeAds' },
  { id: 'business_finance', labelKey: 'themeFinance' },
  { id: 'tutorial_edu', labelKey: 'themeEdu' },
  { id: 'tech_gadget', labelKey: 'themeTech' },
  { id: 'history_facts', labelKey: 'themeHistory' },
  { id: 'culinary_recipe', labelKey: 'themeCulinary' },
  { id: 'travel_vlog', labelKey: 'themeTravel' },
];

export const THEMES: ThemeOption[] = [
  { id: 'cloud', name: 'White', bgClass: 'bg-slate-50', cardClass: 'bg-white border-slate-200 shadow-xl', accentClass: 'bg-blue-600 hover:bg-blue-700 text-white', textClass: 'text-slate-800', inputClass: 'bg-slate-100 border-slate-200 text-slate-900', isDark: false, icon: '☁️' },
  { id: 'lavender', name: 'Purple', bgClass: 'bg-[#f8f7ff]', cardClass: 'bg-white/80 border-purple-100 backdrop-blur-md', accentClass: 'bg-purple-500 hover:bg-purple-600 text-white', textClass: 'text-purple-900', inputClass: 'bg-purple-50/50 border-purple-100 text-purple-900', isDark: false, icon: '🌸' },
  { id: 'mint', name: 'Green', bgClass: 'bg-[#f0fff4]', cardClass: 'bg-white border-emerald-100', accentClass: 'bg-emerald-500 hover:bg-emerald-600 text-white', textClass: 'text-emerald-900', inputClass: 'bg-emerald-50/50 border-emerald-100 text-emerald-900', isDark: false, icon: '🌿' },
  { id: 'cyberpunk', name: 'Night', bgClass: 'bg-slate-950', cardClass: 'bg-slate-900/40 border-fuchsia-500/30 backdrop-blur-xl', accentClass: 'bg-gradient-to-r from-fuchsia-500 to-cyan-500 text-white', textClass: 'text-slate-100', inputClass: 'bg-white/5 border-white/10 text-slate-100', isDark: true, icon: '🌙' }
];
